"""estrutura inicial

Revision ID: e7719734b1cb
Revises: 
Create Date: 2026-09-23 15:51:00.322755
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e7719734b1cb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('fixa', 'variavel', 'ambos', name='categorykind'), nullable=False),
    sa.Column('default_target_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=False)
    op.create_index(op.f('ix_app_settings_user_id'), 'app_settings', ['user_id'], unique=False)
    op.create_table('credit_card_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('card', sa.String(length=60), nullable=True),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installments_total', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_installments_user_id'), 'credit_card_installments', ['user_id'], unique=False)
    op.create_table('daily_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('dinheiro', 'debito', 'credito', 'pix', 'boleto', 'outro', name='paymentmethod'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_expenses_expense_date'), 'daily_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_daily_expenses_user_id'), 'daily_expenses', ['user_id'], unique=False)
    op.create_table('fixed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_expenses_user_id'), 'fixed_expenses', ['user_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_month'), 'incomes', ['month'], unique=False)
    op.create_index(op.f('ix_incomes_user_id'), 'incomes', ['user_id'], unique=False)
    op.create_index(op.f('ix_incomes_year'), 'incomes', ['year'], unique=False)
    op.create_table('variable_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'year', 'month', name='uq_goal_competencia')
    )
    op.create_index(op.f('ix_variable_goals_category_id'), 'variable_goals', ['category_id'], unique=False)
    op.create_index(op.f('ix_variable_goals_user_id'), 'variable_goals', ['user_id'], unique=False)
    op.create_table('fixed_expense_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_expense_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fixed_expense_id'], ['fixed_expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixed_expense_id', 'year', 'month', name='uq_fixed_payment_competencia')
    )
    op.create_index(op.f('ix_fixed_expense_payments_fixed_expense_id'), 'fixed_expense_payments', ['fixed_expense_id'], unique=False)
    op.create_index(op.f('ix_fixed_expense_payments_month'), 'fixed_expense_payments', ['month'], unique=False)
    op.create_index(op.f('ix_fixed_expense_payments_year'), 'fixed_expense_payments', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixed_expense_payments_year'), table_name='fixed_expense_payments')
    op.drop_index(op.f('ix_fixed_expense_payments_month'), table_name='fixed_expense_payments')
    op.drop_index(op.f('ix_fixed_expense_payments_fixed_expense_id'), table_name='fixed_expense_payments')
    op.drop_table('fixed_expense_payments')
    op.drop_index(op.f('ix_variable_goals_user_id'), table_name='variable_goals')
    op.drop_index(op.f('ix_variable_goals_category_id'), table_name='variable_goals')
    op.drop_table('variable_goals')
    op.drop_index(op.f('ix_incomes_year'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_user_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_month'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_fixed_expenses_user_id'), table_name='fixed_expenses')
    op.drop_table('fixed_expenses')
    op.drop_index(op.f('ix_daily_expenses_user_id'), table_name='daily_expenses')
    op.drop_index(op.f('ix_daily_expenses_expense_date'), table_name='daily_expenses')
    op.drop_table('daily_expenses')
    op.drop_index(op.f('ix_credit_card_installments_user_id'), table_name='credit_card_installments')
    op.drop_table('credit_card_installments')
    op.drop_index(op.f('ix_app_settings_user_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
